version: "3"

services:
  detalhador-de-chamados:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    container_name: detalhador-de-chamados
    volumes:
      - "./src/:/home/src/"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    container_name: db
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d

    ports:
      - ${DB_PORT}:${DB_PORT}

networks:
  default:
    external:
      name: schedula-network
